/**************
 * IWANNAFLY  *
 *            *
 *  prealpha  *
 *  mk7.0.0   *
 **************/

/* this program currently requires a second terminal; this may be anything
 * that can be passed to the program as argv[1] and fopened "r+". stderr
 * should also be redirected to the same file. invocation might be:
 *
 * Iwannafly /dev/pts/1 savefile 2>/dev/pts/1
 *
 * eventually, all three relevant windows will be generated by the program
 * itself, allowing it to be launched without an stdio.
 */

#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "raylib.h"
#include "raymath.h"
#include "rlightsbindings.h"

#define SCREENH 800
#define SCREENV 600
#define EYEFOV 120.0
#define FILMFOV 55.0

//define G_EARTH 9.80665
//define G_MOON 1.625
//define G_MARS 3.72076

pthread_mutex_t NCURSLOCK_O = PTHREAD_MUTEX_INITIALIZER;
pthread_mutex_t NCURSLOCK_I = PTHREAD_MUTEX_INITIALIZER;

struct shared_mutex CAMERALOCK_R = calloc(sizeof(struct shared_mutex));
pthread_mutex_t CAMERALOCK_W = PTHREAD_MUTEX_INITIALIZER;
Camera3d CAMERA = calloc(1,sizeof(Camera3D));
int CAMERAMODE = calloc(1,sizeof(int));

struct shared_mutex RENDERLOCK_R = calloc(sizeof(struct shared_mutex));
pthread_mutex_t RENDERLOCK_W = PTHREAD_MUTEX_INITIALIZER;
struct renderstack * RENDERTAPE = calloc(1,sizeof(struct renderstack));

struct shared_mutex CACHELOCK_R = calloc(sizeof(struct shared_mutex));
pthread_mutex_t CACHELOCK_W = PTHREAD_MUTEX_INITIALIZER;
struct scalarcache * CACHE = calloc(1,sizeof(struct scalarcache));

struct shared_mutex MASTERLOCK_R = calloc(sizeof(struct shared_mutex));
pthread_mutex_t MASTERLOCK_W = PTHREAD_MUTEX_INITIALIZER;
struct funstack * TOPLEVELSTACK = calloc(1,sizeof(struct funstack));

ncurskeydispatcher (struct mutex_flags * mutex) {
	wint_t tmp;
	pthread_mutex_lock(&NCURSLOCK_I);
	pthread_mutex_wait(&NCURSLOCK_O);
	get_wch(tmp);
	pthread_mutex_unlock(&NCURSLOCK_I);
	switch (tmp) {
#include wchswitchcase.cinclude
		}
	}

topleveldispatcher (int opcode,int argc,scalar *(*argv)[]) {
	switch (opcode) {
	case 0 : return 0;
#include opswitchcase.cinclude
	}}

bool TOPLEVELNAMES_P[] = 
#include opnamesP.carray
;

char *TOPLEVELNAMES[] =
#include opnames.carray
;

renderdispatcher (int opcode,Texture2D texture,Vector3 position) {
	switch (opcode) {
#include renderswitchcase.cinclude
	}}

void render (struct renderstackmutex * shared) {
	for (;;) {
		shared_mutex_inc(&CAMERALOCK_R,&CAMERALOCK_W);
		shared_mutex_inc(&RENDERLOCK_R,&RENDERLOCK_W);
		for (uint64_t n = 1;shared->bsy;n++) {
			if (!n) {
				fprintf(stderr,"%s",strerror(EAGAIN));
				}
			}
		for (struct renderobject * this = shared->r->index;this != NULL;this = this->next) {
			renderdispatcher(this->opcode,this->data->texture,*(this->location));
			}
		shared_mutex_dec(&CAMERALOCK_R);
		shared_mutex_dec(&RENDERLOCK_R);
		}
	}

main (int argc, char *argv[]) {
	if (argc < 2) {
		printf("usage: %s <tty> ...\n",argv[0]);
		exit(1);
		}
	initialize(argv[1]);
	pthread_t curskeyid;
	pthread_t rendererid;
	pthread_create(&curskeyid,NULL,render,NCURSLOCK);
	pthread_create(&rendererid,NULL,render,RENDERGUARD);
	for (;;) {
		if (topleveldispatcher(TOPLEVELSTACK->index->fun,TOPLEVELSTACK->index->argc,TOPLEVELSTACK->index->argv)) {
			perror();
			fprintf(stderr,"Flywheel Runtime Error! (main (forever (topleveldispatcher (%s))))\n",TOPLEVELDISPATCHNAMES_P[TOPLEVELSTACK->index->fun] ? TOPLEVELDISPATCHNAMES[TOPLEVELSTACK->index->fun] : "missingno");
			exit(1);
			}
		funstack_shunt(TOPLEVELSTACK);
		}
	fprintf(stderr,"In girum imus nocte et consumimur igni");
	exit(42);
	}

initialize (char * devname) {
	TOPLEVELSTACK->index = calloc(1,sizeof(struct fwheelnode));
	TOPLEVELSTACK->index->fun = __OPCODE_LOADPLAYER__;
	TOPLEVELSTACK->index->n = 1;

	TOPLEVELSTACK->index->next = calloc(1,sizeof(struct fwheelnode));
	TOPLEVELSTACK->index->next->fun = __OPCODE_LOADWORLD__;
	TOPLEVELSTACK->index->next->n = 1;

	TOPLEVELSTACK->index->next->next = calloc(1,sizeof(struct fwheelnode));
	TOPLEVELSTACK->index->next->next->fun = 0;
	TOPLEVELSTACK->index->next->next->n = -1;

	TOPLEVELSTACK->prev = calloc(1,sizeof(struct fwheelnode));
	TOPLEVELSTACK->prev->fun = 0;
	TOPLEVELSTACK->prev->n = -1;

	TOPLEVELSTACK->index->next->next->next = TOPLEVELSTACL->prev;
	TOPLEVELSTACK->prev->next = TOPLEVELSTACK->index;

	

	FILE * dev = fopen(devname,"r+");
	if (dev == NULL) {
		perror();
		fprintf(stderr,"(Not a typewriter?)\n");
		printf("usage: %s <tty> ...\n",argv[0]);
		exit(1);
		}
	newterm(NULL,dev,dev);
	raw();
	noecho();
	keypad();

	InitWindow(SCREENH,SCREENV,"IWANNAFLY DEVTEST 2");
	CAMERA.position = (Vector3){0.0,0.0,0.0};
	CAMERA.target = (Vector3){1.0,0.0,0.0};
	CAMERA.up = (Vector3){0.0,1.0,0.0};
	CAMERA.fovy = EYEFOV;
	CAMERA.type = CAMERA_PERSPECTIVE;
	SetCameraMode(CAMERA,CAMERA_FIRST_PERSON);
	CAMERAMODE = CAMERA_FIRST_PERSON;
	SetTargetFPS(60);
	}
